project_id = "qjkojiamexufuxsrupjq"

[functions.update-xmr-price]
verify_jwt = false

[functions.moderate-comment]
verify_jwt = false

[functions.site-assistant]
verify_jwt = false

[functions.trocador-new-rate]
verify_jwt = false

[functions.trocador-new-trade]
verify_jwt = false

[functions.trocador-trade-status]
verify_jwt = false

[functions.sync-trocador-coins]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.simpleswap-api]
verify_jwt = false

[functions.nanogpt-tts]
verify_jwt = false

[functions.therapy-chat]
verify_jwt = false

[functions.voice-clone]
verify_jwt = false

[functions.voice-generate]
verify_jwt = false

[functions.voice-voices]
verify_jwt = false
